apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: rhsso-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable'

