kind: CronJob
apiVersion: batch/v1
metadata:
  name: cronjob-etcd-backup
  namespace: openshift-config
  labels:
    purpose: etcd-backup
spec:
  schedule: "58 15 * * *"
  startingDeadlineSeconds: 200
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          nodeSelector:
            node-role.kubernetes.io/master: ''
          restartPolicy: Never
          activeDeadlineSeconds: 200
          serviceAccountName: etcd-backup
          hostNetwork: true
          containers:
            - resources:
                requests:
                  cpu: 300m
                  memory: 250Mi
              terminationMessagePath: /dev/termination-log
              name: etcd-backup
              command:
                - /bin/sh
                - '-c'
                - >-
                  /root/etcd-backup.sh && ls -1 /assets/backup/* | sort -r | tail -n +6 | xargs rm -rf > /dev/null 2>&1
              securityContext:
                privileged: true
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: certs
                  mountPath: /etc/ssl/etcd/
                - name: conf
                  mountPath: /etc/etcd/
                - name: kubeconfig
                  mountPath: /etc/kubernetes/
                - name: etcd-backup-script
                  mountPath: /root/etcd-backup.sh
                  subPath: etcd-backup.sh
                - name: scripts
                  mountPath: /usr/local/bin
                - name: oc
                  mountPath: /usr/bin/oc
              terminationMessagePolicy: FallbackToLogsOnError
              image: >-
                quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:74ade3d34106717d8fc5b5bd0931582dad5a7a5e1d1fe197e67b8ff2187749ec
          serviceAccount: etcd-backup
          tolerations:
            - operator: Exists
              effect: NoSchedule
            - operator: Exists
              effect: NoExecute
          volumes:
            - name: certs
              hostPath:
                path: /etc/kubernetes/static-pod-resources/etcd-member
                type: ''
            - name: conf
              hostPath:
                path: /etc/etcd
                type: ''
            - name: kubeconfig
              hostPath:
                path: /etc/kubernetes
                type: ''
            - name: scripts
              hostPath:
                path: /usr/local/bin
                type: ''
            - name: oc
              hostPath:
                path: /usr/bin/oc
                type: ''
            - name: etcd-backup-script
              configMap:
                name: etcd-backup-script
                defaultMode: 493

