apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-streams-og
  namespace: dev-kafka-edaapp
spec:
  targetNamespaces:
  - dev-kafka-edaapp
---                                  
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  namespace: dev-kafka-edaapp
spec:
  maturity: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v2.1.0-5
  version: 2.1.0-5
