kind: Deployment
apiVersion: apps/v1
metadata:
  name: amq-streams-cluster-operator-v2.1.0-5
  namespace: dev-kafka-edaapp
  labels:
    olm.deployment-spec-hash: 6c8fb6f477
    olm.owner: amqstreams.v2.1.0-5
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: dev-kafka-edaapp
    operators.coreos.com/amq-streams.dev-kafka-edaapp: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amq-streams-cluster-operator
      strimzi.io/kind: cluster-operator  
  template:
    metadata:
      labels:
        rht.comp_ver: '2.1'
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2022.Q2
        name: amq-streams-cluster-operator
        com.company: Red_Hat
        strimzi.io/kind: cluster-operator
        rht.subcomp_t: infrastructure
        rht.subcomp: cluster-operator
        rht.comp: AMQ_Streams
    spec:
      serviceAccountName: strimzi-cluster-operator
      schedulerName: default-scheduler
      containers:
        - resources: {}
          name: strimzi-cluster-operator
          env:
            - name: FIPS_MODE
              value: disabled
