apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quay-enterprise

bases:
  - ../../base

patchesJson6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: quay-operator
      namespace: quay-enterprise
    path: patch-channel.yaml