apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operators
  namespace: openshift-marketplace
spec:
  image: quay.internal.cloudapp.net/import2/redhat/redhat-operator-index:v4.10
  sourceType: grpc