apiVersion: v1
items:
- apiVersion: platform.stackrox.io/v1alpha1
  kind: Central
  metadata:
    annotations:
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      argocd.argoproj.io/sync-wave: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"platform.stackrox.io/v1alpha1","kind":"Central","metadata":{"annotations":{"argocd.argoproj.io/sync-options":"SkipDryRunOnMissingResource=true","argocd.argoproj.io/sync-wave":"1"},"name":"central","namespace":"stackrox"},"spec":{"central":{"exposure":{"loadBalancer":{"enabled":false,"port":443},"nodePort":{"enabled":false},"route":{"enabled":true}},"persistence":{"persistentVolumeClaim":{"claimName":"stackrox-db"}}},"egress":{"connectivityPolicy":"Online"},"scanner":{"analyzer":{"scaling":{"autoScaling":"Enabled","maxReplicas":5,"minReplicas":2,"replicas":2}},"scannerComponent":"Enabled"}}}
    creationTimestamp: "2022-05-13T10:53:39Z"
    finalizers:
    - uninstall-helm-release
    generation: 1
    name: central
    namespace: stackrox
    resourceVersion: "72769219"
    uid: d5095eaf-ae07-4e48-b8a7-86f6d899eacd
  spec:
    central:
      exposure:
        loadBalancer:
          enabled: false
          port: 443
        nodePort:
          enabled: false
        route:
          enabled: true
      persistence:
        persistentVolumeClaim:
          claimName: stackrox-db
    egress:
      connectivityPolicy: Online
    scanner:
      analyzer:
        scaling:
          autoScaling: Enabled
          maxReplicas: 5
          minReplicas: 2
          replicas: 2
      scannerComponent: Enabled
  status:
    central:
      adminPassword:
        info: |-
          A password for the 'admin' user has been automatically generated and stored in the "password" entry of the central-htpasswd secret.
          To view the password, run
            oc -n stackrox get secret central-htpasswd -o go-template='{{index .data "password" | base64decode}}'
    conditions:
    - lastTransitionTime: "2022-05-13T10:54:00Z"
      message: |
        StackRox 3.69.1 has been installed.



        Thank you for using StackRox!
      reason: InstallSuccessful
      status: "True"
      type: Deployed
    - lastTransitionTime: "2022-05-13T10:54:00Z"
      status: "True"
      type: Initialized
    - lastTransitionTime: "2022-05-26T12:26:01Z"
      message: 'patch error: Route.route.openshift.io "central" is invalid: spec.tls.destinationCACertificate:
        Invalid value: "redacted destination ca certificate data": passthrough termination
        does not support certificates'
      reason: ReconcileError
      status: "True"
      type: Irreconcilable
    - lastTransitionTime: "2022-05-13T10:54:00Z"
      message: No proxy configuration is desired
      reason: NoProxyConfig
      status: "False"
      type: ProxyConfigFailed
    - lastTransitionTime: "2022-05-13T10:54:00Z"
      status: "False"
      type: ReleaseFailed
    deployedRelease: {}
    productVersion: 3.69.1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
