apiVersion: v1
data:
  CSI_LOG_LEVEL: "5"
  CSI_PLUGIN_TOLERATIONS: |2-

    - key: node-role.kubernetes.io/infra
      operator: Equal
      effect: NoSchedule
    - key: node-role.kubernetes.io/infra
      operator: Equal
      effect: NoExecute
    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
  CSI_PROVISIONER_TOLERATIONS: |2-

    - key: node-role.kubernetes.io/infra
      operator: Equal
      effect: NoSchedule
    - key: node-role.kubernetes.io/infra
      operator: Equal
      effect: NoExecute
    - key: node.ocs.openshift.io/storage
      operator: Equal
      value: "true"
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      operator: Exists
kind: ConfigMap
metadata:
  name: rook-ceph-operator-config
  namespace: openshift-storage
