apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: azure-monitor-clf-ds
      namespace: azure-monitor-clf
    path: patch-image.yaml