---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#generatorOptions:
#  disableNameSuffixHash: true

resources:
  - default-project-template.yaml

# attempt to patch project.config.openshift.io/cluster
# eg
# $ oc patch project.config.openshift.io/cluster \
#    --type=merge \
#    -p '{"spec":{"projectRequestTemplate":{"name":"project-request"}}}'
patchesJson6902:
  - target:
      group: config.openshift.io
      version: v1
      kind: Project
      name: cluster
      namespace: openshift-config
    path: patch-cluster-project-template.yaml