apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: btg-cluster-admin-role
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: btg_np-mgmt_account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
