apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: quay-user-pass
  namespace: dso-juice-shop
  annotations:
      tekton.dev/docker-0: <Quay repo> # Described below for quay
spec:
  backendType: vault
  template:
    type: kubernetes.io/basic-auth
    annotations:
        tekton.dev/docker-0: <Quay repo> # Described below for quay
  data:
    # inside Hashicorp it will be pathed as secret/dso-quey-robot - requires /data/ here
    - key: secret/data/dso-quey-robot
      name: username
      property: username
    - key: secret/data/dso-quey-robot
      name: password
      property: password
  vaultMountPoint: kubernetes
  vaultRole: dso-quey-robot
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: github-user-pass
  namespace: dso-juice-shop
  annotations:
      tekton.dev/git-0: 'https://github.com'
spec:
  backendType: vault
  template:
    type: kubernetes.io/basic-auth
    metadata:
      annotations:
        tekton.dev/git-0: 'https://github.com'
  data:
    # inside Hashicorp it will be pathed as secret/dso-github-user - requires /data/ here
    - key: secret/data/dso-github-user
      name: username
      property: username
    - key: secret/data/dso-github-user
      name: password
      property: password
  vaultMountPoint: kubernetes
  vaultRole: dso-github-user