kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auditlog-clusterole
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - pods
      - pods/proxy
      - pods/attach
      - pods/exec
      - pods/status
      - pods/log
      - nodes
      - nodes/proxy
      - proxy

