kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-renewal-cr
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
      - patch
    apiGroups:
      - ''
    resources:
      - pods
      - pods/log
      - nodes
      - proxy
      - secrets
