---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: group-sync-operator

secretGenerator:
  - name: keycloak-group-sync
    type: Opaque
    literals:
    - username=group-sync-user
    - password=XXXXXXXXXX

resources:
  - group-sync-cr.yaml
