apiVersion: v1
baseDomain: dnsName
#credentialsMode: Manual
controlPlane: 
  hyperthreading: Enabled   
  name: master
  platform:
    azure:
      osDisk:
        diskSizeGB: 256 
      type: Standard_D8s_v3
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    azure:
      type: Standard_D8s_v3
      osDisk:
        diskSizeGB: 256 
      zones: 
      - "1"
      - "2"
      - "3"
  replicas: 5
metadata:
  name: <ocpName> 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: vnetAddressSpace
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: rg-mgmt-<env>-shared-uks 
    region: uksouth 
    resourceGroupName: rg-<ocpName>-<env>-uks 
    networkResourceGroupName: rg-<ocpName>mgmt-<env>-uks 
    virtualNetwork: vnet-<ocpName>-<env>-uks 
    controlPlaneSubnet: control_plane_subnet 
    computeSubnet: compute_subnet 
    outboundType: UserDefinedRouting 
    cloudName: AzurePublicCloud
pullSecret: 'pullSecretHere' 
fips: true 
sshKey: sshHere
publish: Internal 