---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The QuayRegistry CR doesn't reference a Secret directly, it calls
# it a configBundleSecret. Hence Kustomize can't map it suffix-hashed  
# names automagically, so am disabling it.
generatorOptions:
  disableNameSuffixHash: true

namespace: quay-enterprise

secretGenerator:
  - name: dso-quayregistry-init-config-bundle
    type: Opaque
    files:
    - config.yaml=./quayregistry-config-bundle-data.yaml

resources:
  - quayregistry-cr.yaml
