apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: dso-quay-registry
  namespace: quay-enterprise
spec:
  configBundleSecret: dso-quayregistry-init-config-bundle
  components:
    - kind: objectstorage
      managed: false