---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-sign-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 1G
