apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dso-pl-sign
spec:
  params:
  - name: COSIGN-KEY
    type: string
    default: signing-secrets
  - name: IMAGE
    type: string
    default: 'dso-quay-registry-quay-quay-enterprise.apps.ocp3.azure.dso.digital.mod.uk/dso-project/pipelines-vote-api:latest'
  - name: CHAIN-NAMESPACE
    type: string
    default: chain-workshop
  - name: VAULT-NAMESPACE
    type: string
    default: dso
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  tasks:
  - name: sign-image
    taskRef:
      kind: ClusterTask
      name: vault-sign
    params:
      - name: COSIGN-KEY
        value: "$(params.COSIGN-KEY)"
      - name: IMAGE
        value: "$(params.IMAGE)"
      - name: VAULT-ROLE
        value: pipeline-quay
      - name: VAULT-NAMESPACE
        value: $(params.VAULT-NAMESPACE)
      - name: VAULT-PATH
        value: kv/data/quay        
    workspaces:
      - name: source
        workspace: shared-data

