apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dso-pl-sign-
spec:
  pipelineRef:
    name:  dso-pl-sign
  params:
  - name: VAULT_NAMESPACE
    value: dso2
  workspaces:
  - name: shared-data
    persistentvolumeclaim:
      claimName: vault-sign-pvc
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: vault-sign-pvc
  - name: sonar-settings
    emptyDir: {}
