apiVersion: v1
kind: Namespace
metadata:
  name: openshift-file-integrity
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/display-name: 'File Integrity Operator'
