apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
  - target:
      group: redhatcop.redhat.io
      version: v1alpha1
      kind: GroupSync
      name: keycloak-groupsync
      namespace: group-sync-operator
    path: patch-groupsync-cr.yaml