apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - enable-console-plugin-job.yaml
  - enable-console-plugin-rbac.yaml
  - enable-console-plugin-sa.yaml
  - odf-console-plugin.yaml
  - odf-subscription.yaml
  - odf-operatorgroup.yaml
  - odf-namespace.yaml
