apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: juice-shop-pd-trigger
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: dso-pl-pd-juice-shop-
      spec:
        pipelineRef:
          name: dso-pl-pd-juice-shop
        params:
        - name: APP_URL
          value: https://dso-juice-shop.apps.ocp1.azure.dso.digital.mod.uk/#/
        - name: minutes
          value: '5'
