apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: juice-shop-pd-trigger
spec:
  serviceAccountName: pipeline
  name: "tekton"
  bindings:
    - ref: juice-shop-pd-trigger
  template:
    ref: juice-shop-pd-trigger