kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-juice-shop-pd-trigger
  namespace: dso-juice-shop
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: juice-shop-pd-trigger
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: >-
    el-juice-shop-pd-trigger-dso-juice-shop.apps.ocp1.azure.dso.digital.mod.uk
  to:
    kind: Service
    name: el-juice-shop-pd-trigger
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: >-
        el-juice-shop-pd-trigger-dso-juice-shop.apps.ocp1.azure.dso.digital.mod.uk
      routerName: default
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps.ocp1.azure.dso.digital.mod.uk
