apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: owasp-zap-run
  namespace: dso-juice-shop
spec:
  params:
    - name: APP_URL
      value: <Application URL>
    - name: minutes
      value: '10'
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: owasp-zap
