apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  labels:
    app.kubernetes.io/name: azure-monitor-clf
spec:
  outputs:
    - name: fluentbit
      type: fluentdForward
      url: 'tcp://azure-monitor-clf-service.azure-monitor-clf.svc.cluster.local:24224'
  pipelines:
    - name: forward-to-fluentbit
      inputRefs:
        - infrastructure
        - application
        - audit
      outputRefs:
        - fluentbit
