apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Set the namespace the forwarder will be deployed to
namespace: azure-monitor-clf

generatorOptions:
  disableNameSuffixHash: true

# Generate the secret that holds Azure creds the CLF uses to forward to Azure Monitor/Analytics
# oc create secret generic azure-monitor-clf-fluentbit-creds -n azure-monitor-clf \
#       --from-literal=WorkspaceId=$WORKSPACE_ID \
#       --from-literal=SharedKey=$SHARED_KEY
# WORKSPACE_ID and SHARED_KEY are set from environment variables passed into the command line.
secretGenerator:
  - name: azure-monitor-clf-fluentbit-creds
    type: Opaque
    envs:
    - azure-monitor-clf.env

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - service.yaml
  - daemonset.yaml
  - clf.yaml