---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-monitor-clf-sa
  namespace: azure-monitor-clf
  labels:
    app.kubernetes.io/name: azure-monitor-clf
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-monitor-clf-role
rules:
- apiGroups: [ "" ]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: azure-monitor-clf-sa-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-monitor-clf-role
subjects:
- kind: ServiceAccount
  name: azure-clf-sa
  namespace: azure-monitor-clf
