apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-deployment-juice-shop-
  name: post-deployment-juice-shop
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: trigger-post-deployment-pipeline
        image: curlimages/curl
        command: ["/bin/sh"]
        args: ["-c", "curl --location --request POST 'https://el-juice-shop-pd-trigger-dso-juice-shop.apps.ocp1.azure.dso.digital.mod.uk/' --header 'Content-Type: application/json' --data-raw '{}' --insecure"]

      restartPolicy: Never
  backoffLimit: 2
