apiVersion: fileintegrity.openshift.io/v1alpha1
kind: FileIntegrity
metadata:
  name: ingress-fileintegrity
spec:
  nodeSelector:
    node-role.kubernetes.io/ingress: ""
  config: {}
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/ingress
      operator: Exists
    - effect: NoExecute
      key: node-role.kubernetes.io/ingress
      operator: Exists
