kind: ConfigMap
apiVersion: v1
metadata:
  name: etcd-backup-script
  namespace: openshift-config
data:
  etcd-backup.sh: |
    #!/bin/bash
    DATE=$(date +%Y%m%dT%H%M%S)
    PATH=$PATH:/usr/bin/oc
    AZ_AZCOPY_URL=$(curl -s -D- https://aka.ms/downloadazcopy-v10-linux | grep ^Location | cut -c11- | tr -d '\r')
    AZ_BLOB_STORE="https://ocp1mg847a4b002a9bd2e2.blob.core.windows.net/etcd"
    AZ_SASKEY="sp=racwl&st=2022-02-02T13:53:36Z&se=2024-02-02T21:53:36Z&spr=https&sv=2020-08-04&sr=c&sig=OdTlnlihV9IVTt3FuMsIBHD%2FMZ7d9j7zaJarTFTpGdY%3D"


    cp /usr/local/bin/cluster-backup.sh /tmp/
    ls -l /tmp/
    sed 's|dl_etcdctl|#dl_etcdctl|g' -i /tmp/cluster-backup.sh
    /tmp/cluster-backup.sh /assets/backup
    if [ $? -eq 0 ]; then
        echo 'Getting Azure azcopy CLI tool...'
        wget -O azcopy.tar.gz "$AZ_AZCOPY_URL" && tar -xf azcopy.tar.gz --strip-components=1
        echo 'Uploading files to Azure'
        ./azcopy copy "/assets/backup/*" $AZ_BLOB_STORE/$DATE/?$AZ_SASKEY --recursive=true
        echo 'Files uploaded to Azure BLOB store' 
       exit 0
    fi

    echo "Backup attempts failed. Please FIX !!!"
    exit 1
