apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - template-infra-machineset.yaml
  - template-ingress-machineset.yaml
  - template-storage-machineset.yaml
  - template-worker-machineset.yaml
