apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: template-storage-machineset
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: replace-me-clustername-clusterid
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: replace-me-clustername-clusterid
      machine.openshift.io/cluster-api-machineset: replace-me-machineset-name
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: replace-me-clustername-clusterid
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: replace-me-machineset-name
    spec:
      metadata:
        labels: {}
      taints: []
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 256
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: replace-me-networkResourceGroup
          userDataSecret:
            name: worker-user-data
          vnet: replace-me-vnet
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: replace-me-zone
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: replace-me-resourceGroup
          kind: AzureMachineProviderSpec
          location: replace-me-location
          vmSize: replace-me-vmSize
          image:
            offer: ''
            publisher: ''
            resourceID: >-
              /resourceGroups/replace-me/providers/Microsoft.Compute/images/replace-me-clusterid
            sku: ''
            version: ''
          managedIdentity: replace-me-identity
          subnet: replace-me-subnet
          apiVersion: azureproviderconfig.openshift.io/v1beta1
