apiVersion: v1
baseDomain: dnsName
controlPlane: 
  hyperthreading: Enabled   
  name: master
  platform:
    azure:
      osDisk:
        diskSizeGB: 256 
      type: Standard_D8s_v3
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    azure:
      type: Standard_D8s_v3
      osDisk:
        diskSizeGB: 256 
      zones: 
      - "1"
      - "2"
      - "3"
  replicas: 5
metadata:
  name: <ocpName> 
networking:
  clusterNetwork:
  - cidr: 172.16.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: vnetAddressSpace
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: rg-mgmt-<env>-shared-uks 
    region: uksouth 
    resourceGroupName: <ocpRG> 
    networkResourceGroupName: <networkRG>
    virtualNetwork: <vnetworkname>
    controlPlaneSubnet: subnet2
    computeSubnet: subnet4
    outboundType: UserDefinedRouting 
    cloudName: AzurePublicCloud
pullSecret: 'pullSecretHere' 
fips: true 
sshKey: sshHere
publish: Internal 