apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  name: gitea-i
  namespace: dso-gitea
spec:
  giteaSsl: true
  giteaAdminUser: dso-mgr
  giteaAdminPassword: "TY4nIRdqv1uxdgDru5cN42aKyZQc8c0Y"
  giteaAdminPasswordLength: 32
  giteaAdminEmail: s.mussa@accenture.com
  giteaVolumeSize: 4Gi
  postgresqlImage: 'quay.internal.cloudapp.net/quay/oc-mirror/rhel8/postgresql-12'
  postgresqlImageTag: e4bfb87a
  postgresqlVolumeSize: 4Gi
  giteaImage: 'quay.internal.cloudapp.net/quay/oc-mirror/gpte-devops-automation/gitea'
  giteaImageTag: latest
