apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-install
  namespace: dso-iac-argocd
spec:
  project: default
  source:
    repoURL: https://gitea-with-admin-dso-gitea.apps.ocp1.azure.dso.digital.mod.uk/dso-mgr/dso-platform.git
    targetRevision: main
    path: dayzero/legion/cohorts/openshift/file-integrity/operator/base
  destination:
    server: https://kubernetes.default.svc
    namespace: dso-iac-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true