apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  annotations:
  name: argocd-manager-argocd
  namespace: argocd-manager
  finalizers:
    - argoproj.io/finalizer
spec:
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    insecure: true
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge      
    service:
      type: ''