apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd-manager8-instance
  namespace: argocd-manager8
spec:
  server:
    insecure: true
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
      p, role:argo-admin, applications, *, */*, allow
      p, role:argo-admin, clusters, get, *, allow
      p, role:argo-admin, repositories, get, *, allow
      p, role:argo-admin, repositories, create, *, allow
      p, role:argo-admin, repositories, update, *, allow
      p, role:argo-admin, repositories, delete, *, allow
      g, system:authenticated, role:argo-admin
    scopes: '[groups]'
  dex:
    openShiftOAuth: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  ha:
    enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  tls:
    ca: {}
  redis:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  controller:
    processors: {}
    resources:
      limits:
        cpu: '2'
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    sharding: {}