apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-logging
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://gitea-i-dso-gitea.apps.ocp1.ocp.local/dso-mgr/dso-platform.git
    targetRevision: main
    path: dayzero/legion/cohorts/openshift/logging/elasticsearch-operator/overlays/stable
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
