kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dso-iac-argocd-doer-rb
  namespace: stackrox
  labels:
    app.kubernetes.io/managed-by: dso-iac-argocd
    app.kubernetes.io/name: dso-iac-argocd-doer
    app.kubernetes.io/part-of: dso-iac-argocd
  annotations:
    argocds.argoproj.io/name: dso-iac-argocd
    argocds.argoproj.io/namespace: dso-iac-argocd
subjects:
  - kind: ServiceAccount
    name: dso-iac-argocd-doer
    namespace: dso-iac-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dso-iac-argocd-doer-clusterrole