kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dso-iac-argocd-doer-clusterrole
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - Get
  - List
  - Watch
  - Patch