apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: ocp1-kp7vk-infra-uksouth3
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: ocp1-kp7vk
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp1-kp7vk
      machine.openshift.io/cluster-api-machineset: ocp1-kp7vk-infra-uksouth3
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp1-kp7vk
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp1-kp7vk-infra-uksouth3
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      taints: 
        - key: node-role.kubernetes.io/infra
          effect: NoSchedule
        - key: node-role.kubernetes.io/infra
          effect: NoExecute
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 256
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: rg-ocp1mgmt-prod-uks
          userDataSecret:
            name: worker-user-data
          vnet: vnet-ocp1-prod-uks
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: '3'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: rg-ocp1-prod-uks
          kind: AzureMachineProviderSpec
          location: uksouth
          vmSize: Standard_D8s_v3
          image:
            offer: ''
            publisher: ''
            resourceID: >-
              /resourceGroups/rg-ocp1-prod-uks/providers/Microsoft.Compute/images/ocp1-kp7vk
            sku: ''
            version: ''
          managedIdentity: ocp1-kp7vk-identity
          subnet: control_plane_subnet
          apiVersion: azureproviderconfig.openshift.io/v1beta1
