---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-compliance

resources:
  - compliance-namespace.yaml
  - compliance-operatorgroup.yaml
  - compliance-subscription.yaml
