---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocs-storagecluster-ceph-rbd
  resources:
    requests:
      storage: 2G
