apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dso-sample-pl-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name:  dso-sample-pl  
  params:
  - name: GIT_URL
    # value: https://github.com/defencedigital/dso-nodejs.git
    value: https://github.com/defencedigital/dso-sample1.git
  - name: REVISION
    value: main
  - name: MANIFEST_GIT_URL
    value: https://github.com/defencedigital/dso-sample1.git
  - name: MANIFEST_REVISION
    value: main
  - name: IMAGE_REPOSITORY
    value: dso-quay-registry-quay-quay-enterprise.apps.ocp1.azure.dso.digital.mod.uk/dso-project   
  - name: SERVICE_VERSION
    value: latest
  - name: REPO_NAME
    value: dso-sample
  - name: SERVICE_NAME
    value: dso-sample
  - name: KUSTOMIZATION_PATH
    value: manifest
  - name: SONAR_HOST_URL
    value: https://sonarqube-edb-dso-tooling-sonar.apps.ocp1.azure.dso.digital.mod.uk/ 
  - name: SONAR_PROJECT_KEY
    value: dso-juice-shop-s0nar-scan-quality-gate
  - name: DEFAULT_IMAGE
    value: dso-sample:latest
  - name: VAULT_NAMESPACE
    value: dso   
  workspaces:
  - name: shared-data
    persistentvolumeclaim:
      claimName: sonar-source-pvc
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: sonar-source-pvc
  - name: sonar-settings
    emptyDir: {}
