apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d2s-monitoring-role
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - core.strimzi.io
  resources:
  - strimzipodsets
  verbs:
  - '*'
