apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: ocp2-fblq5-worker-uksouth2
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: ocp2-fblq5
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp2-fblq5
      machine.openshift.io/cluster-api-machineset: ocp2-fblq5-worker-uksouth2
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp2-fblq5
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp2-fblq5-worker-uksouth2
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          osDisk:
            diskSettings: {}
            diskSizeGB: 256
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: preda-infra-vnet
          userDataSecret:
            name: worker-user-data
          vnet: preda-infra-jdff-vnet
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: '2'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: rg-ocp2-prod-uks
          kind: AzureMachineProviderSpec
          location: uksouth
          vmSize: Standard_E8ds_v5
          image:
            offer: ''
            publisher: ''
            resourceID: >-
              /resourceGroups/rg-ocp2-prod-uks/providers/Microsoft.Compute/images/ocp2-fblq5
            sku: ''
            version: ''
          managedIdentity: ocp2-fblq5-identity
          subnet: subnet4
          apiVersion: machine.openshift.io/v1beta1

