apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: ocp2-fblq5-ingress-uksouth3
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: ocp2-fblq5
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp2-fblq5
      machine.openshift.io/cluster-api-machineset: ocp2-fblq5-ingress-uksouth3
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp2-fblq5
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp2-fblq5-ingress-uksouth3
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          node-role.kubernetes.io/ingress: ""
      taints: 
        - key: node-role.kubernetes.io/ingress
          effect: NoSchedule
          value: "true"
        - key: node-role.kubernetes.io/ingress
          effect: NoExecute
          value: "true"
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 256
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: preda-infra-vnet
          userDataSecret:
            name: worker-user-data
          vnet: preda-infra-jdff-vnet
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: '3'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: rg-ocp2-prod-uks
          kind: AzureMachineProviderSpec
          location: uksouth
          vmSize: Standard_D4s_v3
          image:
            offer: ''
            publisher: ''
            resourceID: >-
              /resourceGroups/rg-ocp2-prod-uks/providers/Microsoft.Compute/images/ocp2-fblq5
            sku: ''
            version: ''
          managedIdentity: ocp2-fblq5-identity
          subnet: subnet3
          apiVersion: azureproviderconfig.openshift.io/v1beta1
