apiVersion: v1
baseDomain: ${base_domain}
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    azure:
      osDisk:
        diskSizeGB: 512
        diskType: ""
      type: Standard_D2s_v3
  replicas: 5
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      osDisk:
        diskSizeGB: 1024
        diskType: ""
      type: Standard_D8s_v3
  replicas: 3
imageContentSources:
- mirrors:
  - ${mirror_address}
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - ${mirror_address}
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
metadata:
  creationTimestamp: null
  name: ${cluster_name}
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: ${worker_subnet}
  - cidr: ${master_subnet}
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    baseDomainResourceGroupName: ${base_domain_rg}
    cloudName: AzureStackCloud
    computeSubnet: ${worker_subnet_name}
    controlPlaneSubnet: ${master_subnet_name}
    networkResourceGroupName: ${ash_network_rg}
    outboundType: Loadbalancer
    region: ${ash_region}
    resourceGroupName: ${rg_name}
    virtualNetwork: ${virtual_network}
    armEndpoint: https://management.${ash_region}.${ash_fqdn}
    outboundType: Loadbalancer
    clusterOSimage: https://${img_cont}.blob.${ash_region}.${ash_fqdn}/rhcos/rhcos-410.84.202201251210-0-azurestack.x86_64.vhd  
publish: Internal
pullSecret: '${pull_secret}'
sshKey: ${ssh_key}
additionalTrustBundle: |
  ${ca_trust_bundle}