apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base

configMapGenerator:
  - name: env-properties
    env: env.properties

generatorOptions:
 disableNameSuffixHash: true
 labels:
   kustomize.generated.resource: "true"


replacements:
  - path: infra-api-cluster-replacements.yaml
  - path: infra-api-machineset-replacements.yaml
  - path: ingress-api-cluster-replacements.yaml
  - path: ingress-api-machineset-replacements.yaml
  - path: storage-api-cluster-replacements.yaml
  - path: storage-api-machineset-replacements.yaml
  - path: worker-api-cluster-replacements.yaml
  - path: worker-api-machineset-replacements.yaml
    
patchesJson6902:
  - target:
      group: machine.openshift.io
      version: v1beta1
      kind: MachineSet
      name: template-infra-machineset
      namespace: openshift-machine-api
    path: patch-infra-machineset.yaml

  - target:
      group: machine.openshift.io
      version: v1beta1
      kind: MachineSet
      name: template-ingress-machineset
      namespace: openshift-machine-api
    path: patch-ingress-machineset.yaml

  - target:
      group: machine.openshift.io
      version: v1beta1
      kind: MachineSet
      name: template-storage-machineset
      namespace: openshift-machine-api
    path: patch-storage-machineset.yaml

  - target:
      group: machine.openshift.io
      version: v1beta1
      kind: MachineSet
      name: template-worker-machineset
      namespace: openshift-machine-api
    path: patch-worker-machineset.yaml

patches:
  - replica-count-infra.yaml
  - replica-count-ingress.yaml
  - replica-count-storage.yaml
  - replica-count-worker.yaml

