- op: replace
  path: /spec/template/spec/providerSpec/value/subnet
  value: subnet3

- op: replace
  path: /spec/template/spec/providerSpec/value/vnet
  value: preda-infra-yjjp-vnet

- op: replace
  path: /spec/template/spec/providerSpec/value/resourceGroup
  value: rg-ocp4-sbox-uks

- op: replace
  path: /spec/template/spec/providerSpec/value/networkResourceGroup
  value: preda-infra-vnet

- op: replace
  path: /spec/template/spec/providerSpec/value/managedIdentity
  value: ocp4-4bn4s-identity

- op: replace
  path: /spec/template/spec/providerSpec/value/vmSize
  value: Standard_D4s_v3

- op: replace
  path: /spec/template/spec/providerSpec/value/image/resourceID
  value: /resourceGroups/rg-ocp4-sbox-uks/providers/Microsoft.Compute/images/ocp4-4bn4s

- op: replace
  path: /spec/template/spec/providerSpec/value/location
  value: uksouth

- op: replace
  path: /spec/template/spec/providerSpec/value/zone
  value: 1

- op: add
  path: /spec/template/spec/metadata/labels
  value:
      node-role.kubernetes.io/infra: ""
      node-role.kubernetes.io/ingress: ""

- op: add
  path: /spec/template/spec/taints/-
  value:
    key: node-role.kubernetes.io/ingress
    effect: NoSchedule

- op: add
  path: /spec/template/spec/taints/-
  value:
    key: node-role.kubernetes.io/ingress
    effect: NoExecute
