apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: ocp3-6px9x-infra-uksouth1
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: ocp3-6px9x
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp3-6px9x
      machine.openshift.io/cluster-api-machineset: ocp3-6px9x-infra-uksouth1
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp3-6px9x
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp3-6px9x-infra-uksouth1
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      taints: 
        - key: node-role.kubernetes.io/infra
          effect: NoSchedule
        - key: node-role.kubernetes.io/infra
          effect: NoExecute
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 256
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: rg-ocp3mgmt-sbox-uks
          userDataSecret:
            name: worker-user-data
          vnet: vnet-ocp3-sbox-uks
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: '1'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: rg-ocp3-sbox-uks
          kind: AzureMachineProviderSpec
          location: uksouth
          vmSize: Standard_D8s_v3
          image:
            offer: ''
            publisher: ''
            resourceID: >-
              /resourceGroups/rg-ocp3-sbox-uks/providers/Microsoft.Compute/images/ocp3-6px9x
            sku: ''
            version: ''
          managedIdentity: ocp3-6px9x-identity
          subnet: control_plane_subnet
          apiVersion: azureproviderconfig.openshift.io/v1beta1
