apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator
  namespace: openshift-operators
spec:
  channel: latest
  source: redhat-operators 
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
  sourceNamespace: openshift-marketplace 
