# Replace cluster-api-machineset (machineset name)
source:
  kind: ConfigMap
  name: env-properties
  fieldPath: data.INGRESS_MACHINESET_NAME
  version: v1
targets:
  - select:
      name: template-ingress-machineset
      kind: MachineSet
    fieldPaths:
    - spec.selector.matchLabels.[machine.openshift.io/cluster-api-machineset]
    - spec.template.metadata.labels.[machine.openshift.io/cluster-api-machineset]
    - metadata.name
