apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak-0
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: keycloak
spec:
  profile: RHSSO
  externalAccess:
    enabled: true
  instances: 1
  keycloakDeploymentSpec:
    experimental:
      env:
      - name: JAVA_TOOL_OPTIONS
        value: -Dcom.redhat.fips=false
