apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: keycloak-0
  labels:
    app: keycloak
spec:
  realm:
    id: sso
    realm: sso
    enabled: True
    displayName: SSO Realm
    eventsListeners:
      - "metrics-listener"
    users:
      - username: realm_admin1
        firstName: Ray
        lastName: Bryan
        email: rbryan@redhat.com
        enabled: True
        emailVerified: False
        realmRoles:
          - offline_access
          - uma_authorization
        clientRoles:
          account:
            - manage-account
            - view-profile
          realm-management:
            - manage-users
            - view-users
            - query-users
            - create-client
  realmOverrides:
    - forFlow: "browser"
      identityProvider: "openshift-v4"
  instanceSelector:
    matchLabels:
      app: keycloak
