apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: keycloak-admin1
  labels:
    app: sso
  namespace: keycloak
spec:
  user:
     username: bryanr
     firstName: Ray
     lastName: Bryan
     email: ray.bryan@digital.mod.uk
     enabled: True
     emailVerified: False
     credentials:
       - temporary: true
         type: password
         value: "password"
     realmRoles:
       - offline_access
       - uma_authorization
     clientRoles:
       account:
         - manage-account
         - view-profile
     realm-management:
       - manage-users
       - view-users
       - query-users
       - create-client
realmSelector:
  matchLabels:
    app: sso
