apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: keycloak-admin2
  labels:
    app: sso
  namespace: keycloak
spec:
  user:
     username: khelas
     firstName: Satinder
     lastName: Khela
     email: satinder.khela@digital.mod.uk
     enabled: True
     emailVerified: False
     credentials:
       - temporary: true
         type: password
         value: "password"
     realmRoles:
       - offline_access
       - uma_authorization
     clientRoles:
       account:
         - manage-account
         - view-profile
     realm-management:
       - manage-users
       - view-users
       - query-users
       - create-client
realmSelector:
  matchLabels:
    app: sso
