apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dso-sample-app
  namespace: pen-test-argo
spec:
  destination:
    namespace: pen-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifest
    repoURL: https://github.com/semirmussa1/dso-sample.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
