apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: Verify-image-pl
spec:
  params:
    - description: URL of the Toolbox image
      name: ToolBoxUrl
      type: string
    - description: URL of the source image (Signature Image in Dev Quay)
      name: srcImageURL
      type: string
    - description: URL of the destination image (Signature Image in Prod Quay)
      name: destImageURL
      type: string
    - description: Credentials of the source registry
      name: srcCreds
      type: string
    - description: Credentials of the destination registry
      name: destCreds
      type: string
    - default: 'true'
      description: Verify the TLS on the src registry endpoint
      name: srcTLSverify
      type: string
    - default: 'true'
      description: Verify the TLS on the dest registry endpoint
      name: destTLSverify
      type: string
    - description: Quay URL (Where the image that will be verified)
      name: quayUrl
      type: string
    - description: Robot Account username
      name: quayUser
      type: string
    - description: Robot Account token
      name: quayToken
      type: string
    - description: Path for image to be verified
      name: repoPath
      type: string
    - description: Image Tag
      name: imageTag
      type: string
  tasks:
    - name: copy-signature-image
      params:
        - name: ToolBoxUrl
          value: $(params.ToolBoxUrl)
        - name: srcImageURL
          value: $(params.srcImageURL)
        - name: destImageURL
          value: $(params.destImageURL)
        - name: srcCreds
          value: $(params.srcCreds)
        - name: destCreds
          value: $(params.destCreds)
        - name: srcTLSverify
          value: $(params.srcTLSverify)
        - name: destTLSverify
          value: $(params.destTLSverify)
      taskRef:
        kind: ClusterTask
        name: skopeo-copy-single
    - name: verify-image
      params:
        - name: ToolBoxUrl
          value: $(params.ToolBoxUrl)
        - name: quayUrl
          value: $(params.quayUrl)
        - name: quayUser
          value: $(params.quayUser)
        - name: quayToken
          value: $(params.quayToken)
        - name: repoPath
          value: $(params.repoPath)
        - name: imageTag
          value: $(params.imageTag)
      taskRef:
        kind: ClusterTask
        name: cosign-verify
      runAfter:
      - copy-signature-image