apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: skopeo-copy-single
spec:
  description: |-
    Skopeo is a command line tool for working with remote image registries.
    Skopeo doesn’t require a daemon to be running while performing its operations. 
    In particular, the handy skopeo command called copy will ease the whole image copy operation. 
    The copy command will take care of copying the image from internal.registry to production.registry. 
    If your production registry requires credentials to login in order to push the image, skopeo can handle that as well.
  params:
  - default: ""
    description: URL of the Toolbox Image
    name: ToolBoxUrl
    type: string
  - default: ""
    description: URL of the source image 
    name: srcImageURL
    type: string
  - default: ""
    description: URL of the destination image
    name: destImageURL
    type: string
  - default: ""
    description: Credentials of the source registry
    name: srcCreds
    type: string
  - default: ""
    description: Credentials of the destination registry
    name: destCreds
    type: string
  - default: "true"
    description: Verify the TLS on the src registry endpoint
    name: srcTLSverify
    type: string
  - default: "true"
    description: Verify the TLS on the dest registry endpoint
    name: destTLSverify
    type: string
  steps:
  - image: $(params.ToolBoxUrl)
    name: skopeo-copy
    resources: {}
    script: |
      #! /bin/bash
      CMD="skopeo copy docker://$(params.srcImageURL) docker://$(params.destImageURL) --src-creds $(params.srcCreds) --dest-creds $(params.destCreds) --src-tls-verify=$(params.srcTLSverify) --dest-tls-verify=$(params.destTLSverify)"

      ${CMD} &> result
      cat result